# Manually triggered pipeline to generate shipping builds of the CI artifacts
trigger: none

variables:
- template: settings/common.yml

resources:
  repositories:
  - repository: build-tools
    type: git
    endpoint: Analog
    name: Analog/mixedrealitytoolkit.build
    ref: mru-ue

stages:
- stage: Windows
  dependsOn: []
  pool:
    name: $(AgentPool)
  jobs:
  - job:
    timeoutInMinutes: 90
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
      submodules: true
    - checkout: build-tools

    - template: templates/common.yml
      parameters:
        Configuration: 'Shipping'

    - template: templates/build-android.yml
      parameters:
        Configuration: 'Shipping'

    # TODO: Sign UXTools binaries

    - task: NuGetCommand@2
      inputs:
        command: 'pack'
        packagesToPack: '$(UXTSourceDir)/UXTools.nuspec'
        packDestination: '$(NuGetStagingDir)'
        basePath: '$(UXToolsPluginOutputDir)'
      displayName: 'Create UXTools NuGet package'

    # TODO: Sign UXToolsExamples binaries

    - task: NuGetCommand@2
      inputs:
        command: 'pack'
        packagesToPack: '$(UXTSourceDir)/UXToolsExamples.nuspec'
        packDestination: '$(NuGetStagingDir)'
        basePath: '$(UXToolsExamplesPluginOutputDir)'
      displayName: 'Create UXToolsExamples NuGet package'

    # TODO: Sign NuGet packages

    - task: PublishBuildArtifacts@1
      displayName: 'Publish NuGet packages build artifacts'
      inputs:
        ArtifactName: 'NuGet Packages'
        PathtoPublish: '$(NuGetStagingDir)'
